use custom build for sabnzbd
Used custom building  of image 
Reduce size of image 

Idee  from Lsio

diff --git a/nightly/docker-sabnzbd-nightly/Dockerfile b/nightly/docker-sabnzbd-nightly/Dockerfile
--- a/nightly/docker-sabnzbd-nightly/Dockerfile
+++ b/nightly/docker-sabnzbd-nightly/Dockerfile
@@ -1,63 +1,83 @@
-FROM ghcr.io/linuxserver/baseimage-ubuntu:focal
-
-# set version label
+FROM alpine:3.15
+ARG TARGETPLATFORM
+ARG BUILDPLATFORM
 ARG VERSION
-ARG DEBIAN_FRONTEND="noninteractive"
-ENV HOME="/config" \
+ARG OVERLAY=v2.2.0.3
+
+# environment variables
+ENV PS1="$(whoami)@$(hostname):$(pwd)\\$ " \
+HOME="/config" \
+TERM="xterm" \
 PYTHONIOENCODING=utf-8
 
 RUN \
-  echo "***** install gnupg ****" && \
-  apt-get update -yqq && \
-  apt-get install -yqq \
-    gnupg && \
-  echo "***** add sabnzbd repositories ****" && \
-  apt-key adv --keyserver hkp://keyserver.ubuntu.com:11371 --recv-keys 0x98703123E0F52B2BE16D586EF13930B14BB9F05F && \
-  echo "deb http://ppa.launchpad.net/jcfp/nobetas/ubuntu focal main" >> /etc/apt/sources.list.d/sabnzbd.list && \
-  echo "deb-src http://ppa.launchpad.net/jcfp/nobetas/ubuntu focal main" >> /etc/apt/sources.list.d/sabnzbd.list && \
-  echo "deb http://ppa.launchpad.net/jcfp/sab-addons/ubuntu focal main" >> /etc/apt/sources.list.d/sabnzbd.list && \
-  echo "deb-src http://ppa.launchpad.net/jcfp/sab-addons/ubuntu focal main" >> /etc/apt/sources.list.d/sabnzbd.list && \
-  echo "**** install packages ****" && \
-  apt-get update && \
-  apt-get install -yqq \
+  echo "**** install build packages ****" \
+  && apk add --no-cache --virtual=build-dependencies tar curl jq \
+  && set -x && ARCH=$(uname -m) \
+  && case "${ARCH}" in \
+     x86_64) \
+        ARCH='amd64' && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+        ;; \
+     armv7) \
+        ARCH='arm' && \
+        curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
+        chmod +x /usr/bin/qemu-${ARCH}-static && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+     ;; \
+     armhf) \
+        ARCH='armhf' && \
+        curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
+        chmod +x /usr/bin/qemu-${ARCH}-static && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+     ;; \
+     aarch64) \
+        ARCH='aarch64' && \
+        curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
+        chmod +x /usr/bin/qemu-${ARCH}-static && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+      ;; \
+     *) echo >&2 "Error: unsupported architecture ($ARCH)"; exit 1 ;; \
+  esac \
+  && \
+  apk del --purge build-dependencies && rm -rf /tmp/* && \
+  echo "**** starting install sabnzbd packages ****" && \
+  apk add -U --update --no-cache --virtual=build-dependencies \
+    build-base \
+    gcc \
     libffi-dev \
-    libssl-dev \
-    p7zip-full \
-    par2-tbb \
+    openssl-dev \
+    python3-dev && \
+  apk add  -U --update --no-cache \
+    curl \
+    tar \
+    p7zip \
+    par2cmdline \
     python3 \
-    python3-cryptography \
-    python3-distutils \
-    python3-pip \
-    python3-setuptools \
-    unrar \
-    jq && \
+    py3-pip && \
+  apk add -U --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/main unrar && \
+  SABNZBD_VERSION=$(curl -s https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]') && \
   mkdir -p /app/sabnzbd && \
   curl -o \
     /tmp/sabnzbd.tar.gz -L \
-    "https://github.com/sabnzbd/sabnzbd/releases/download/${VERSION}/SABnzbd-${VERSION}-src.tar.gz" && \
+    "https://github.com/sabnzbd/sabnzbd/releases/download/${SABNZBD_VERSION}/SABnzbd-${SABNZBD_VERSION}-src.tar.gz" && \
   tar xf \
     /tmp/sabnzbd.tar.gz -C \
     /app/sabnzbd --strip-components=1 && \
   cd /app/sabnzbd && \
-  pip3 install -U --no-cache-dir pip && \
-  pip install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/ubuntu/ \
+  python3 -m pip install --upgrade pip && \
+  pip3 install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/alpine/ \
+    wheel \
     apprise \
     pynzb \
     requests && \
-  pip install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/ubuntu/ -r requirements.txt && \
+  pip3 install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/alpine/ -r requirements.txt && \
+  pip3 cache purge && \
   echo "**** cleanup ****" && \
-  ln -s \
-    /usr/bin/python3 \
-    /usr/bin/python && \
-  apt-get purge --auto-remove -y \
-    libffi-dev \
-    libssl-dev \
-    python3-pip && \
-  apt-get clean && \
+  ln -s /usr/bin/python3 /usr/bin/python && \
+  apk del --purge build-dependencies && \
   rm -rf \
     /tmp/* \
-    /var/lib/apt/lists/* \
-    /var/tmp/* \
     $HOME/.cache
 
 COPY ./apps/docker-sabnzbd/root/ /
