Update Dockerfile

diff --git a/base/docker-alpine/Dockerfile b/base/docker-alpine/Dockerfile
--- a/base/docker-alpine/Dockerfile
+++ b/base/docker-alpine/Dockerfile
@@ -1,27 +1,7 @@
-FROM alpine:3.14
+FROM alpine:3.15
 ARG TARGETPLATFORM
 ARG BUILDPLATFORM
 ARG VERSION
-
-RUN \
- echo "**** update build packages ****" && \
-   apk --quiet --no-cache --no-progress update && \
-   apk --quiet --no-cache --no-progress upgrade && \
- echo "**** install build packages ****" && \
-   apk add --no-cache bash curl tzdata xz coreutils shadow curl tar jq
-
-RUN set -x && OVERLAY_ARCH=$(uname -m) \
-  && case "${OVERLAY_ARCH}" in \
-    x86_64) OVERLAY_ARCH='amd64';; \
-    arm) OVERLAY_ARCH='armhf';; \
-    aarch64) OVERLAY_ARCH='aarch64';; \
-    *) echo "unsupported architecture"; exit 1 ;; \
-  esac \
-  && OVERLAY_VERSION=$(curl -sL "https://api.github.com/repos/just-containers/s6-overlay/releases/latest" | jq -r '. | .tag_name') \
-  && curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY_VERSION}/s6-overlay-${OVERLAY_ARCH}.tar.gz | tar xvzf - -C / \
-  && apk del --no-cache curl && apk del --purge &&  rm -rf /tmp/*
-
-COPY ./base/docker-alpine/patch/ /tmp/patch
 
 # environment variables
 ENV PS1="$(whoami)@$(hostname):$(pwd)\\$ " \
@@ -29,38 +9,45 @@ HOME="/root" \
 TERM="xterm"
 
 RUN \
- echo "**** install build packages ****" && \
- apk add --no-cache --virtual=build-dependencies curl patch tar && \
- echo "**** install runtime packages ****" && \
- apk add --no-cache ca-certificates coreutils procps shadow tzdata bash curl bc findutils coreutils && \
- echo "**** create abc user and make our folders ****" && \
- groupmod -g 1000 users && \
- useradd -u 911 -U -d /config -s /bin/false abc && \
- usermod -G users abc && \
- mkdir -p \
-	/app \
-	/config \
-	/defaults \
-	/system && \
- mv /usr/bin/with-contenv /usr/bin/with-contenvb && \
- patch -u /etc/s6/init/init-stage2 -i /tmp/patch/etc/s6/init/init-stage2.patch
-
-RUN \
-  QARCH=$(uname -m) \
-  && case "${QARCH}" in \
-  aarch64) \
-     curl -o /usr/bin/qemu-${QARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
-     chmod +x /usr/bin/qemu-${QARCH}-static; \
-  ;; \
-  arm) \
-     curl -o /usr/bin/qemu-${QARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
-     chmod +x /usr/bin/qemu-${QARCH}-static; \
-  ;; \
+  echo "**** install build packages ****" \
+  && apk add --no-cache --virtual=build-dependencies tar curl jq \
+  && OVERLAY=$(curl -sL "https://api.github.com/repos/just-containers/s6-overlay/releases/latest" | jq -r '. | .tag_name') \
+  && set -x && ARCH=$(uname -m) \
+  && case "${ARCH}" in \
+     x86_64) \
+        ARCH='amd64' && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+        ;; \
+     armv7) \
+        ARCH='arm' && \
+        curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
+        chmod +x /usr/bin/qemu-${ARCH}-static && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+     ;; \
+     armhf) \
+        ARCH='armhf' && \
+        curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
+        chmod +x /usr/bin/qemu-${ARCH}-static && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+     ;; \
+     aarch64) \
+        ARCH='aarch64' && \
+        curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
+        chmod +x /usr/bin/qemu-${ARCH}-static && \
+        curl -L -s https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY}/s6-overlay-${ARCH}.tar.gz | tar xvzf - -C / ; \
+      ;; \
+     *) echo >&2 "Error: unsupported architecture ($ARCH)"; exit 1 ;; \
   esac \
   && \
-  apk del --purge build-dependencies && \
-  echo "**** cleanup ****" && \
-  rm -rf /tmp/*
+  apk del --purge build-dependencies && rm -rf /tmp/* && \
+  echo "**** install runtime packages ****" && \
+     apk add --no-cache apk-tools bash busybox coreutils shadow && \
+  echo "**** create abc user and make our folders ****" && \
+     groupmod -g 1000 users && \
+     useradd -u 911 -U -d /config -s /bin/false abc && \
+     usermod -G users abc && \
+     mkdir -p /{app,config,defaults,system} && \
+     rm -rf /var/cache/apk/*
 
 COPY ./base/docker-alpine/root/ /
 
