Update Dockerfile

diff --git a/apps/docker-mount/Dockerfile b/apps/docker-mount/Dockerfile
--- a/apps/docker-mount/Dockerfile
+++ b/apps/docker-mount/Dockerfile
@@ -39,7 +39,15 @@ RUN \
 
 RUN \
   rm -rf /tmp/* && \
-     if [[ ${ARCH} != "x86_64" ]]; then
+  set -x && ARCH=$(uname -m) && \
+  case "${ARCH}" in \
+     x86_64) ARCH='amd64' ;; \
+     armv7) ARCH='arm' ;; \
+     armhf) ARCH='armhf' ;; \
+     aarch64) ARCH='aarch64' ;; \
+     *) echo >&2 "Error: unsupported architecture ($ARCH)"; exit 1 ;; \
+  esac && \
+     if [[ "${ARCH}" != "x86_64" ]]; then
         curl -o /usr/bin/qemu-${ARCH}-static -L "https://lsio-ci.ams3.digitaloceanspaces.com/qemu-${ARCH}-static" && \
         chmod +x /usr/bin/qemu-${ARCH}-static; \
      fi && \
